import type { Metadata } from 'next'
import { Inter, Playfair } from 'next/font/google'

import '../globals.css'
import { ThemeProvider } from '@/providers/theme.provider'
import { HeaderView } from '@/views/header.view/header.view'
import { FooterView } from '@/views/footer.view/footer.view'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

const playfair = Playfair({
  weight: '900',
  style: 'italic',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: React.ReactNode
  params: {
    locale: string
  }
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body
        className={`${inter.className} ${playfair.variable} `}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex w-full min-h-screen flex-col">
            <HeaderView />
            {children}
            <FooterView />
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
